services:
  
  usersdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    
  configsdb:
    image: mongo
    
  infrastructure-identity:
    image: infrastructure-identity
    build:
      context: .
      dockerfile: Infrastructure/Identity/Dockerfile

  remoteconfig-webapi:
    image: remoteconfig-webapi
    build:
      context: .
      dockerfile: Services/RemoteConfig/RemoteConfig.WebApi/Dockerfile

  usermanagement-webapi:
    image: usermanagement-webapi
    build:
      context: .
      dockerfile: Services/UserManagement/UserManagement.WebApi/Dockerfile

volumes:
  mongo_data: