services:
  
  usersdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    
  configsdb:
    image: mongo
    
  cache:
    image: redis
    
  infrastructure-identity:
    image: infrastructure-identity
    build:
      context: .
      dockerfile: Infrastructure/Identity/Dockerfile
      
  infrastructure-gateway:
    image: infrastructure-gateway
    build:
      context: .
      dockerfile: Infrastructure/Gateway/Gateway.Ocelot/Dockerfile

  remoteconfig-webapi:
    image: remoteconfig-webapi
    build:
      context: .
      dockerfile: Services/RemoteConfig/RemoteConfig.WebApi/Dockerfile

  usermanagement-webapi:
    image: usermanagement-webapi
    build:
      context: .
      dockerfile: Services/UserManagement/UserManagement.WebApi/Dockerfile

volumes:
  mongo_data: