<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>RemoteConfig.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
      <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
      <PackageReference Include="AutoMapper" Version="15.0.1" />
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RemoteConfig.Application\RemoteConfig.Application.csproj" />
      <ProjectReference Include="..\RemoteConfig.Persistence\RemoteConfig.Persistence.csproj" />
    </ItemGroup>

</Project>
